import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { Grade } from '../../../../shared/models/grade';

@Component({
  selector: 'app-add-grade',
  templateUrl: './add-grade.component.html',
  styleUrls: ['./add-grade.component.css']
})
export class AddGradeComponent implements OnInit {
  @Output() onSave: EventEmitter<Grade> = new EventEmitter<Grade>();
  @Input() displayAddDialog: boolean=false;// Add input for dialog display
  form: FormGroup;

  constructor(private formBuilder: FormBuilder) {
    this.form = this.createForm();
  }

  ngOnInit(): void {
  }

  createForm() {
    return this.formBuilder.group({
      libele: [null, Validators.required]
    });
  }
  

  save(): void {
    if (this.form.valid) {
      const newGrade: Grade = {
       grade_id : null, // Id will be generated by the backend
        libele: this.form.controls['libele'].value
      };
      this.onSave.emit(newGrade);
      this.hideDialog();
    } else {
      // Form is invalid, display validation errors
      this.markFormGroupTouched(this.form);
    }
  }

  markFormGroupTouched(formGroup: FormGroup) {
    Object.values(formGroup.controls).forEach(control => {
      control.markAsTouched();

      if (control instanceof FormGroup) {
        this.markFormGroupTouched(control);
      }
    });
  }

  showDialog(): void {
    this.displayAddDialog = true;
  }

  hideDialog(): void {
    this.displayAddDialog = false;
  }
}
